import io
import re
from pathlib import Path

import pandas as pd
import psycopg
import streamlit as st
from psycopg import sql

DB_URL = st.secrets["SUPABASE_DB_URL"]
FIXED_SCHEMAS = ["public", "private"]


def sanitize_identifier(name: str) -> str:
    """테이블명/컬럼명을 Postgres 식별자로 사용 가능하게 정리"""
    name = str(name).strip().lower()
    name = re.sub(r"[^\w]+", "_", name, flags=re.UNICODE)
    name = re.sub(r"^(\d)", r"_\1", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name or "col"


def make_unique_identifiers(names):
    """중복 컬럼명 방지"""
    seen = {}
    out = []

    for name in names:
        base = sanitize_identifier(name)
        if base not in seen:
            seen[base] = 0
            out.append(base)
        else:
            seen[base] += 1
            out.append(f"{base}_{seen[base]}")

    return out


def infer_pg_type(series: pd.Series, column_name: str = "") -> str:
    """
    PostgreSQL 컬럼 타입 추론
    - 문자열 -> text
    - 정수 -> bigint
    - 실수 -> double precision
    - bool -> boolean
    - 학번/id/번호/code 류는 식별자로 보고 text 권장
    """
    col = str(column_name).strip().lower()

    if any(keyword in col for keyword in ["학번", "id", "번호", "code"]):
        return "text"

    s = series.dropna()
    if s.empty:
        return "text"

    if pd.api.types.is_bool_dtype(series):
        return "boolean"
    if pd.api.types.is_integer_dtype(series):
        return "bigint"
    if pd.api.types.is_float_dtype(series):
        return "double precision"

    numeric = pd.to_numeric(s, errors="coerce")
    if numeric.notna().all():
        if (numeric % 1 == 0).all():
            return "bigint"
        return "double precision"

    return "text"


def ensure_schema_exists(cur, schema: str):
    cur.execute(
        """
        select exists (
            select 1
            from information_schema.schemata
            where schema_name = %s
        )
        """,
        (schema,),
    )
    exists = cur.fetchone()[0]

    if not exists:
        cur.execute(
            sql.SQL("create schema if not exists {}").format(
                sql.Identifier(schema)
            )
        )


def table_exists(cur, schema: str, table_name: str) -> bool:
    cur.execute(
        """
        select exists (
            select 1
            from information_schema.tables
            where table_schema = %s and table_name = %s
        )
        """,
        (schema, table_name),
    )
    return cur.fetchone()[0]


def get_existing_columns(cur, schema: str, table_name: str) -> dict:
    cur.execute(
        """
        select column_name, data_type
        from information_schema.columns
        where table_schema = %s and table_name = %s
        order by ordinal_position
        """,
        (schema, table_name),
    )
    return {row[0]: row[1] for row in cur.fetchall()}


def get_tables_in_schema(cur, schema: str) -> list[str]:
    cur.execute(
        """
        select table_name
        from information_schema.tables
        where table_schema = %s
          and table_type = 'BASE TABLE'
        order by table_name
        """,
        (schema,),
    )
    return [row[0] for row in cur.fetchall()]


def get_table_columns(cur, schema: str, table_name: str) -> list[tuple[str, str]]:
    cur.execute(
        """
        select column_name, data_type
        from information_schema.columns
        where table_schema = %s and table_name = %s
        order by ordinal_position
        """,
        (schema, table_name),
    )
    return [(row[0], row[1]) for row in cur.fetchall()]


def create_table(cur, schema: str, table_name: str, df: pd.DataFrame):
    col_defs = []

    for col in df.columns:
        pg_type = infer_pg_type(df[col], col)
        col_defs.append(
            sql.SQL("{} {}").format(sql.Identifier(col), sql.SQL(pg_type))
        )

    create_sql = sql.SQL(
        """
        create table if not exists {}.{} (
            id bigint generated by default as identity primary key,
            {}
        )
        """
    ).format(
        sql.Identifier(schema),
        sql.Identifier(table_name),
        sql.SQL(", ").join(col_defs),
    )

    cur.execute(create_sql)


def add_missing_columns(cur, schema: str, table_name: str, df: pd.DataFrame):
    existing = get_existing_columns(cur, schema, table_name)

    for col in df.columns:
        if col not in existing:
            pg_type = infer_pg_type(df[col], col)
            alter_sql = sql.SQL(
                """
                alter table {}.{}
                add column {} {}
                """
            ).format(
                sql.Identifier(schema),
                sql.Identifier(table_name),
                sql.Identifier(col),
                sql.SQL(pg_type),
            )
            cur.execute(alter_sql)


def copy_dataframe(cur, conn, schema: str, table_name: str, df: pd.DataFrame):
    """DataFrame을 PostgreSQL COPY로 빠르게 적재"""
    export_df = df.copy().where(pd.notnull(df), None)

    buffer = io.StringIO()
    export_df.to_csv(buffer, index=False, header=False, na_rep="\\N")
    buffer.seek(0)

    copy_sql = sql.SQL(
        """
        copy {}.{} ({})
        from stdin with (format csv, null '\\N')
        """
    ).format(
        sql.Identifier(schema),
        sql.Identifier(table_name),
        sql.SQL(", ").join(sql.Identifier(col) for col in export_df.columns),
    )

    with cur.copy(copy_sql.as_string(conn)) as copy:
        while chunk := buffer.read(8192):
            copy.write(chunk)


def fetch_table_data(
    cur,
    schema: str,
    table_name: str,
    columns: list[str],
    search_column: str,
    keyword: str,
    limit: int,
):
    base_query = sql.SQL("select * from {}.{}").format(
        sql.Identifier(schema),
        sql.Identifier(table_name),
    )

    params = []
    where_clause = sql.SQL("")

    keyword = keyword.strip()
    if keyword:
        like_value = f"%{keyword}%"

        if search_column == "전체":
            conditions = [
                sql.SQL("cast({} as text) ilike %s").format(sql.Identifier(col))
                for col in columns
            ]
            where_clause = sql.SQL(" where ") + sql.SQL(" or ").join(conditions)
            params.extend([like_value] * len(columns))
        else:
            where_clause = sql.SQL(
                " where cast({} as text) ilike %s"
            ).format(sql.Identifier(search_column))
            params.append(like_value)

    if "id" in columns:
        order_clause = sql.SQL(" order by {} asc").format(sql.Identifier("id"))
    else:
        order_clause = sql.SQL("")

    limit_clause = sql.SQL(" limit %s")
    params.append(limit)

    final_query = base_query + where_clause + order_clause + limit_clause

    cur.execute(final_query, params)
    rows = cur.fetchall()
    headers = [desc[0] for desc in cur.description]

    return pd.DataFrame(rows, columns=headers)


st.set_page_config(page_title="CSV → Supabase 업로드", layout="wide")
st.title("CSV → Supabase 자동 테이블 생성 및 조회")

tab1, tab2 = st.tabs(["업로드 / 테이블 생성", "검색 / 조회"])


with tab1:
    st.subheader("CSV 업로드 후 테이블 생성")
    uploaded_file = st.file_uploader("CSV 파일 업로드", type=["csv"])

    if uploaded_file is not None:
        raw_name = Path(uploaded_file.name).stem
        suggested_table_name = sanitize_identifier(raw_name)

        col1, col2 = st.columns([2, 1])
        with col1:
            table_name = st.text_input(
                "생성/추가할 테이블 이름",
                value=suggested_table_name,
            )
        with col2:
            schema = st.selectbox(
                "스키마",
                options=FIXED_SCHEMAS,
                index=0,
                key="upload_schema",
            )

        df = pd.read_csv(uploaded_file)
        original_columns = list(df.columns)
        cleaned_columns = make_unique_identifiers(original_columns)
        df.columns = cleaned_columns

        st.subheader("미리보기")
        st.dataframe(df.head(20), use_container_width=True)

        inferred_types = pd.DataFrame({
            "원본 컬럼명": original_columns,
            "DB 컬럼명": cleaned_columns,
            "예상 DB 타입": [infer_pg_type(df[col], col) for col in df.columns]
        })

        st.subheader("예상 DB 컬럼 타입")
        st.caption("CSV 컬럼이 Supabase(PostgreSQL)에서 어떤 타입으로 생성될지 보여줍니다.")
        st.dataframe(inferred_types, use_container_width=True)

        if st.button("테이블 생성 후 업로드", type="primary"):
            try:
                with psycopg.connect(DB_URL) as conn:
                    with conn.cursor() as cur:
                        ensure_schema_exists(cur, schema)

                        if not table_exists(cur, schema, table_name):
                            create_table(cur, schema, table_name, df)
                        else:
                            add_missing_columns(cur, schema, table_name, df)

                        copy_dataframe(cur, conn, schema, table_name, df)
                    conn.commit()

                st.session_state["last_schema"] = schema
                st.session_state["last_table"] = table_name
                st.success(f"{schema}.{table_name} 테이블에 {len(df)}개 행 업로드 완료")

            except Exception as e:
                st.error(f"업로드 실패: {e}")


with tab2:
    st.subheader("테이블 검색 및 조회")

    browse_schema = st.selectbox(
        "조회할 스키마",
        options=FIXED_SCHEMAS,
        index=0 if st.session_state.get("last_schema", "public") == "public" else 1,
        key="browse_schema",
    )

    try:
        with psycopg.connect(DB_URL) as conn:
            with conn.cursor() as cur:
                tables = get_tables_in_schema(cur, browse_schema)

        if not tables:
            st.info(f"{browse_schema} 스키마에 조회할 테이블이 없습니다.")
        else:
            default_table = st.session_state.get("last_table")
            if default_table in tables:
                default_index = tables.index(default_table)
            else:
                default_index = 0

            browse_table = st.selectbox(
                "조회할 테이블",
                options=tables,
                index=default_index,
            )

            with psycopg.connect(DB_URL) as conn:
                with conn.cursor() as cur:
                    column_info = get_table_columns(cur, browse_schema, browse_table)

            columns = [col for col, _ in column_info]

            info_df = pd.DataFrame(column_info, columns=["컬럼명", "DB 타입"])
            with st.expander("테이블 컬럼 정보 보기"):
                st.dataframe(info_df, use_container_width=True)

            search_col1, search_col2, search_col3 = st.columns([2, 2, 1])

            with search_col1:
                search_column = st.selectbox(
                    "검색 컬럼",
                    options=["전체"] + columns,
                )
            with search_col2:
                keyword = st.text_input("검색어", value="")
            with search_col3:
                limit = st.number_input(
                    "조회 행 수",
                    min_value=1,
                    max_value=500,
                    value=50,
                    step=10,
                )

            if st.button("검색 / 조회", type="primary"):
                try:
                    with psycopg.connect(DB_URL) as conn:
                        with conn.cursor() as cur:
                            result_df = fetch_table_data(
                                cur=cur,
                                schema=browse_schema,
                                table_name=browse_table,
                                columns=columns,
                                search_column=search_column,
                                keyword=keyword,
                                limit=int(limit),
                            )

                    st.write(f"조회 결과: {len(result_df)}건")
                    st.dataframe(result_df, use_container_width=True)

                except Exception as e:
                    st.error(f"조회 실패: {e}")

            st.caption("검색어를 비워두면 최근 데이터부터 limit 개수만큼 조회합니다.")

    except Exception as e:
        st.error(f"테이블 목록 조회 실패: {e}")